version: '3.8'
services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: PLAYGROUND_DB
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: 'mysql --user=root --password=password --execute "SHOW DATABASES;"'