version: '3.8'
services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: PLAYGROUND_DB
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "./sql/db_creation_scheme.sql:/docker-entrypoint-initdb.d/1.sql"
    healthcheck:
      test: 'mysql --user=root --password=password --execute "SHOW DATABASES;"'
  server:
    container_name: server
    build:
      context: ./
    ports:
      - 3001:3001
    environment:
     - SEQUELIZE_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy